# Generated by Django 3.2.8 on 2021-11-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
    ]
