# Generated by Django 3.2.8 on 2021-11-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_rename_user_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='responses',
            field=models.JSONField(default={}),
        ),
    ]
